name: Build and publish Docker images
on:
  release:
    types:
      - "published"

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: DrOfAwesomeness/example-app-server
  CLIENT_IMAGE_NAME: DrOfAwesomeness/example-app-client

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine metadata for server image
        id: servermeta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}
      - name: Determine metadata for client image
        id: clientmeta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.CLIENT_IMAGE_NAME }}
      - name: Build and push the server image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: ${{ steps.servermeta.outputs.tags }}
          labels: ${{ steps.servermeta.outputs.labels }}
      - name: Build and push the client image
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: ${{ steps.clientmeta.outputs.tags }}
          labels: ${{ steps.clientmeta.outputs.labels }}